#!/bin/bash
# vim:ts=4

GENDIR="../../generated"

nodes="$(find . -mindepth 1 -maxdepth 1 -type d -print)"
if [ -z "$nodes" ]; then
	echo "Can't find any subdirectories"
	exit 1
fi

function doGen {
	for x in ./*.in; do
		grep -v '^##' $x
	done
}

for node in $nodes; do
	pushd $node >/dev/null || exit 1
	[ -d $GENDIR ] || (mkdir -p $GENDIR || exit 1)
	doGen >$GENDIR/$node.torrc
	popd >/dev/null
done
